import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar/navbar";
import { toast, Toaster } from "sonner";
import Footer from "./_components/footer/footer";
import MySessionProvider from "./_providers/mySessionProvider";
import Providers from "./_components/Tanstackproviders/providers";
import CardContextProvider from "./_context/CardContextProvider";
import { getUserCart } from "./_actions/Card.actions";
import { getUserWishlist } from "./_actions/wishlist.action";
import CategoriesDropdown from "./_components/CategoriesDropdown/CategoriesDropdown";


const exo = Exo({
  subsets: ["latin"],
  weight: ["500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

 const userData = await getUserCart()
 console.log("userData ==>", userData)


 const userWishlist = await getUserWishlist()
 console.log("userWishlist ==>", userWishlist)

  return (
    <html lang="en">
      <body className={exo.className}>
        {/* <SessionProvider> */}
        <MySessionProvider>
          {/* Context */}
          <CardContextProvider userData={userData} userWishlist = {userWishlist}>

            <Providers>
              <Navbar categoriesDropdown={<CategoriesDropdown />} />
              <Toaster />
              {children}
              <Footer />
            </Providers>

          </CardContextProvider>
        </MySessionProvider>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
